name: flutter_learn_full
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  equatable: ^2.0.5 # https://pub.dev/packages/equatable

  # Google
  json_annotation: ^4.8.0 # https://pub.dev/packages/json_annotation
  json_serializable: ^6.6.0 # https://pub.dev/packages/json_serializable

  # States
  provider: ^6.0.5 # https://pub.dev/packages/provider

  # Network
  dio: ^4.0.6 # https://pub.dev/packages/dio

  # Cache
  shared_preferences: ^2.0.16 # https://pub.dev/packages/shared_preferences

  cupertino_icons: ^1.0.5 # https://pub.dev/packages/cupertino_icons

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/apple-and-book-png-transparent-apple-and-book-images-274565.png
    - assets/png/
    - assets/lottie/
    - assets/translations/
