name: flutter_full_learn
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Animation
  lottie: ^2.2.0 # https://pub.dev/packages/lottie

  # Core
  equatable: ^2.0.5 # https://pub.dev/packages/equatable
  collection: any # https://pub.dev/packages/collection

  # Context
  kartal: ^2.7.0 # https://pub.dev/packages/kartal

  # Google
  image_picker: ^0.8.6+1 # https://pub.dev/packages/image_picker
  json_annotation: ^4.8.0 # https://pub.dev/packages/json_annotation
  json_serializable: ^6.6.0 # https://pub.dev/packages/json_serializable

  # States
  provider: ^6.0.5 # https://pub.dev/packages/provider
  flutter_mobx: ^2.0.6+5 # https://pub.dev/packages/flutter_mobx

  # Network
  dio: ^4.0.4 # https://pub.dev/packages/dio
  vexana: ^2.8.0 # https://pub.dev/packages/vexana/install

  # Cache
  shared_preferences: ^2.0.16 # https://pub.dev/packages/shared_preferences

  cupertino_icons: ^1.0.5 # https://pub.dev/packages/cupertino_icons
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3 # https://pub.dev/packages/build_runner/install
  mobx_codegen: ^2.1.1 # https://pub.dev/packages/mobx_codegen
  mockito: ^5.3.2 # https://pub.dev/packages/mockito

flutter:
  uses-material-design: true

  assets:
    - assets/apple-and-book-png-transparent-apple-and-book-images-274565.png
    - assets/png/
    - assets/lottie/
    - assets/translations/
